# config.yaml.example - 配置文件模板
content_dir: "./content"      # 内容文件目录
output_dir: "./output"        # 分析结果输出目录

# AI服务配置
ai:
  provider: "openai"          # 可选: openai, claude, local
  api_key: ""                 # API密钥，建议通过环境变量 AI_API_KEY 设置
  base_url: ""                # 自定义API地址（可选）
  model: "gpt-3.5-turbo"      # 使用的模型

# 图片分析配置
image:
  max_size: 10485760          # 最大文件大小 10MB
  supported_ext:              # 支持的图片格式
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".gif"
    - ".bmp"
    - ".webp"
  enable_ocr: false           # 是否启用OCR文字识别

# 分析配置
analysis:
  min_word_count: 50          # 最小字数要求
  max_word_count: 1000        # 推荐最大字数
  score_weights:              # 评分权重
    content_quality: 0.25     # 内容质量权重
    engagement: 0.20          # 互动性权重
    visual: 0.15              # 视觉效果权重
    title: 0.15               # 标题质量权重
    readability: 0.15         # 可读性权重
    trend_relevance: 0.10     # 趋势相关性权重
